### ISSUE TITLE
Recompilation issue at DRGN0/5156

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Script-Recompiler#17]
Virage 2 grab attack
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at org.legendofdragoon.scripting.Lexer.parseParam(Lexer.java:301)
	at org.legendofdragoon.scripting.Lexer.parseParams(Lexer.java:247)
	at org.legendofdragoon.scripting.Lexer.lexLine(Lexer.java:215)
	at org.legendofdragoon.scripting.Lexer.lex(Lexer.java:78)
	at org.legendofdragoon.scripting.Shell.main(Shell.java:150)

**Comment by avionanx** [comment]
Probably this call?
```
call Battle::scriptRenderBattleHudBackground, 0xa0, 0x32, 0xd0, 0x10, inl[:LABEL_77[stor[8]]] ; x, y, width, height

**Comment by avionanx** [comment]
The method takes 5 parameters but theres 4 parameters in SC meta, fifth parameter has no ScriptParam annotation in SC
